### ISSUE TITLE
Incompatibility with Busco 5.7

### ISSUE THREAD

**Issue by muffato** [genomehubs/blobtoolkit#223]
Hi Rich,

We had to migrate to Busco 5.7 because the v5.5 biocontainer is contaminated by Anaconda-licensed packages. Busco runs, but the pipeline fails down the line in the `BLOBTOOLKIT_CREATEBLOBDIR` stage, using the v4.4.0 release of docker.io/genomehubs/blobtoolkit.

```
Command executed:

  blobtools replace \
      --bedtsvdir windowstats \
      --meta GCA_927399515.1.yaml \
      --taxdump new_taxdump \
      --taxrule buscogenes \
      --busco lineage01/full_table.tsv --busco lineage02/full_table.tsv --busco lineage03/full_table.tsv --busco lineage04/full_table.tsv --busco lineage05/full_table.tsv --busco lineage06/full_table.tsv --busco lineage07/full_table.tsv \
      --hits GCA_927399515.1.txt \
      --threads 6 \
      --evalue 1.0e-25 --hit-count 10 \
      GCA_927399515.1
 
  cat <<-END_VERSIONS > versions.yml
  "SANGERTOL_BLOBTOOLKIT:BLOBTOOLKIT:BLOBTOOLS:BLOBTOOLKIT_CREATEBLOBDIR":
      blobtoolkit: $(btk --version | cut -d' ' -f2 | sed 's/v//')
  END_VERSIONS

Command exit status:
  1

Command output:
  Reading all TSV files in windowstats
  Loading parsed taxdump

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/btk_env/bin/blobtools", line 8, in <module>
      sys.exit(cli())
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
      sys.exit(subcommand())
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 203, in cli
      main(args)
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 149, in main
      parsed = field["module"].parse(
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 541, in parse
      blast = parse_blast(
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 59, in parse_blast
      "end": int(end),
  ValueError: invalid literal for int() with base 10: '717583|+'

Work dir:
  /lustre/scratch123/tol/teams/tolit/users/mm49/nextflow/blobtoolkit/work/4a/265542815477b8f9a7d4e8e73fa877
```

The problem is in `GCA_927399515.1.txt` which is the output of _diamond blastp_:
```
# Busco 5.5
OV656677.1:717002-717583=60954at2157=multi      914234  354     OV656677.1:717002-717583=60954at2157=multi      tr|M2QZH2|M2QZH2_CERS8  96.2    183     7       0       1       183     38      220     1.45e-127 354
OV656677.1:717002-717583=60954at2157=multi      742152  353     OV656677.1:717002-717583=60954at2157=multi      tr|A0A2H3K186|A0A2H3K186_WOLCO  95.6    183     8       0       1       183     38      220     2.64e-127  353
# Busco 5.7
OV656677.1:717002-717583|+=60954at2157=multi        914234  354     OV656677.1:717002-717583|+=60954at2157=multi    tr|M2QZH2|M2QZH2_CERS8  96.2    183     7       0       1       183     38220      1.45e-127       354
OV656677.1:717002-717583|+=60954at2157=multi        742152  353     OV656677.1:717002-717583|+=60954at2157=multi    tr|A0A2H3K186|A0A2H3K186_WOLCO  95.6    183     8       0       1       183        38      220     2.64e-127       353
```

You can see that the entries are identical in terms of gene, coordinate, alignment score, etc, but the sequence name has got an extra `|+`.

The difference can be traced back to `busco_sequences/multi_copy_busco_sequences/60954at2157.faa`:
```
# Busco 5.5
>OV656677.1_1212 # 717002 # 717583 # 1 # ID=4_1212;partial=00;start_type=GTG;rbs_motif=None;rbs_spacer=None;gc_cont=0.579
MPVTKLGRLVKDGKIKSMEEIYLFSLPVKEFQIVDFFLPKLKDEVMKIMPVQKQTRAGQR
TRFKAFVAVGDFDGHVGLGVKCAKEVATAIRGAIVLAKLSIVPVRRGYWGAALGEPHTVP
SKVSGKVGSVMCRLIPAPRGTGLVAAPASKRLLQMAGVEDCYTQSKGSTATMGNFLKATF
AAVRIHVVDSCMV*
>OV656677.1_1227 # 725203 # 725784 # 1 # ID=4_1227;partial=00;start_type=GTG;rbs_motif=None;rbs_spacer=None;gc_cont=0.572
MPVTKLGRLVKDGKIKEIEEIYLFSLPVKEYQIIDTLLPKLKDEVMKIMPVQKQTRAGQR
TRFKAFVAVGDFDGHVGLGVKCAKEVATAIRGAIVLAKLSVVPVRRGYWGAALGEPHTVP
SKVSGKVGSVMCRLIPAPRGTGLVAAPASKRLLQFAGVEDCYTQSKGSTATMGNFLKATF
AAVRIHVVDSCMV*
```
```
# Busco 5.7
>OV656677.1:717002-717583|+
MPVTKLGRLVKDGKIKSMEEIYLFSLPVKEFQIVDFFLPKLKDEVMKIMPVQKQTRAGQR
TRFKAFVAVGDFDGHVGLGVKCAKEVATAIRGAIVLAKLSIVPVRRGYWGAALGEPHTVP
SKVSGKVGSVMCRLIPAPRGTGLVAAPASKRLLQMAGVEDCYTQSKGSTATMGNFLKATF
AAVRIHVVDSCMV*
>OV656677.1:725203-725784|+
MPVTKLGRLVKDGKIKEIEEIYLFSLPVKEYQIIDTLLPKLKDEVMKIMPVQKQTRAGQR
TRFKAFVAVGDFDGHVGLGVKCAKEVATAIRGAIVLAKLSVVPVRRGYWGAALGEPHTVP
SKVSGKVGSVMCRLIPAPRGTGLVAAPASKRLLQFAGVEDCYTQSKGSTATMGNFLKATF
AAVRIHVVDSCMV*
```

**Comment by rjchallis** [comment]
Thanks for tracing the source of this error, I've pushed a potential fix. Could you try running this example with `docker.io/genomehubs/blobtoolkit:develop` to confirm that it works for your example, then I can make a new release

**Comment by muffato** [comment]
Thanks for looking into it. It looks like there's still an issue:
```
Command executed:

  blobtools replace \
      --bedtsvdir windowstats \
      --meta GCA_927399515.1.yaml \
      --taxdump new_taxdump \
      --taxrule buscogenes \
      --busco lineage01/full_table.tsv --busco lineage02/full_table.tsv --busco lineage03/full_table.tsv --busco lineage04/full_table.tsv --busco lineage05/full_table.tsv --busco lineage06/full_table.tsv --busco lineage07/full_table.tsv \
      --hits GCA_927399515.1.txt \
      --threads 6 \
      --evalue 1.0e-25 --hit-count 10 \
      GCA_927399515.1
  
  cat <<-END_VERSIONS > versions.yml
  "SANGERTOL_BLOBTOOLKIT:BLOBTOOLKIT:BLOBTOOLS:BLOBTOOLKIT_CREATEBLOBDIR":
      blobtoolkit: $(btk --version | cut -d' ' -f2 | sed 's/v//')
  END_VERSIONS

Command exit status:
  1

Command output:
  Reading all TSV files in windowstats
  Loading parsed taxdump

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/btk_env/bin/blobtools", line 8, in <module>
      sys.exit(cli())
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
      sys.exit(subcommand())
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 203, in cli
      main(args)
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 149, in main
      parsed = field["module"].parse(
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 541, in parse
      blast = parse_blast(
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 54, in parse_blast
      seq_id, start, end = re.split(r"[:-]", parts[0])
  ValueError: too many values to unpack (expected 3)

Work dir:
  /lustre/scratch123/tol/teams/tolit/users/mm49/nextflow/blobtoolkit/work/7f/7d3b729687718707634658f58d2b63
```

```
mm49@tol22-head2:/lustre/scratch123/tol/teams/tolit/users/mm49/nextflow/blobtoolkit/work/7f/7d3b729687718707634658f58d2b63 $ grep -F 717002 GCA_927399515.1.txt 
OV656677.1:717002-717583|+=60954at2157=multi    914234  354     OV656677.1:717002-717583|+=60954at2157=multi    tr|M2QZH2|M2QZH2_CERS8  96.2    183     7       0       1       183     38      220     1.45e-127 354
OV656677.1:717002-717583|+=60954at2157=multi    742152  353     OV656677.1:717002-717583|+=60954at2157=multi    tr|A0A2H3K186|A0A2H3K186_WOLCO  95.6    183     8       0       1       183     38      220     2.64e-127  353
```

**Comment by tkchafin** [comment]
I think I am still getting the error: 
```
INFO:    Using cached SIF image
Reading all TSV files in windowstats
Loading parsed taxdump
Traceback (most recent call last):
  File "/opt/conda/envs/btk_env/bin/blobtools", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
    sys.exit(subcommand())
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 203, in cli
    main(args)
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 149, in main
    parsed = field["module"].parse(
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 541, in parse
    blast = parse_blast(
  File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 59, in parse_blast
    "end": int(end),
ValueError: invalid literal for int() with base 10: '717583|+'
```

Command used: 
```
singularity exec --bind $PWD:$PWD -H $PWD docker://docker.io/genomehubs/blobtoolkit:develop /bin/bash ./.command.sh > output.log 2>&1
```

**Comment by tkchafin** [comment]
@muffato I am getting the same error and it looks like it is choking on inputs like this: 
```
918816at2759_5643_1:000746V656676.1:915870-917297
```

**Comment by tkchafin** [comment]
It looks like it is having a problem with this line: 
```
918816at2759_5643_1:000746|OV656676.1:915870-917297|-=1090038at2759=single	5643	428	918816at2759_5643_1:000746|OV656676.1:915870-917297|-=1090038at2759=single	tr|A0A060S6E5|A0A060S6E5_PYCCI	62.3	334	103	2	1	312	479	811	4.13e-147	428
```

Output with some prints added: 
```
query: 918816at2759_5643_1:000746|OV656676.1:915870-917297|-=1090038at2759=single
parts: ['918816at2759_5643_1:000746V656676.1:915870-917297', '1090038at2759', 'single']
Debugging - parts[0]: 918816at2759_5643_1:000746V656676.1:915870-917297
Traceback (most recent call last):
  File "/nfs/users/nfs_t/tc25/mambaforge/bin/blobtools", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/lustre/scratch123/tol/teams/tolit/users/tc25/blobtool_test/blobtoolkit/src/blobtools/blobtools.py", line 105, in cli
    sys.exit(subcommand())
             ^^^^^^^^^^^^
  File "/lustre/scratch123/tol/teams/tolit/users/tc25/blobtool_test/blobtoolkit/src/blobtools/lib/add.py", line 203, in cli
    main(args)
  File "/lustre/scratch123/tol/teams/tolit/users/tc25/blobtool_test/blobtoolkit/src/blobtools/lib/add.py", line 149, in main
    parsed = field["module"].parse(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/scratch123/tol/teams/tolit/users/tc25/blobtool_test/blobtoolkit/src/blobtools/lib/hits.py", line 545, in parse
    blast = parse_blast(
            ^^^^^^^^^^^^
  File "/lustre/scratch123/tol/teams/tolit/users/tc25/blobtool_test/blobtoolkit/src/blobtools/lib/hits.py", line 58, in parse_blast
    seq_id, start, end = re.split(r"[:|-]", parts[0])
    ^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)
```

**Comment by rjchallis** [comment]
Looks like I'm still having problems with PR notifications so missed #224 until after I'd committed some changes. The parsing should be a bit more robust, but names like the example given by @tkchafin shouldn't be getting into the blastp results file (assuming the original seqids were like OV656676.1) so I wonder if this is related to an [issue with handling sequence names](https://gitlab.com/ezlab/busco/-/issues/748) that was introduced around BUSCO 5.6.2 and fixed in 5.8.0?

There should be a new develop container for testing

**Comment by tkchafin** [comment]
Hi, I'm getting error now trying to pull the container: 

```
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
INFO:    Fetching OCI image...
INFO:    Extracting OCI image...
FATAL:   Unable to handle docker://docker.io/genomehubs/blobtoolkit:develop uri: while building SIF from layers: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: unpack entry: opt/conda/pkgs/blobtk-0.5.3-py39_0/lib/python3.9/site-packages/blobtk-0.5.3.dist-info/INSTALLER: link: unpriv.link: unpriv.wrap target: no such file or directory
```

**Comment by rjchallis** [comment]
I'll try a singularity pull to check if I can reproduce this, but is there a chance this is hitting a cached version of the container? I'd left the leading `/` off the `CONDA_DIR` variable a build or 2 ago, which would explain this, but I've just checked and the current develop container image has `CONDA_DIR=/opt/conda`

**Comment by rjchallis** [comment]
ah, OK - I just got the same error even with `SINGULARITY_DISABLE_CACHE=yes` I'll take a closer look at what might be going wrong

**Comment by rjchallis** [comment]
I think this is a singularity version thing. `singularity pull docker://genomehubs/blobtoolkit:develop` works fine with singularity versions 3.11.4 and 4.0.3. I can only reproduce your error when using singularity 4.1.0 - hopefully this will work if you retry with another singularity version

**Comment by rjchallis** [comment]
Just checked and it also builds fine with Singularity 4.2.1 so whatever the problem was seems fixed in singularity now

**Comment by rjchallis** [comment]
This is now in the 4.4.2 container so you should be able to move off develop

**Comment by muffato** [comment]
Thanks Rich. FYI we found another issue when testing the pipeline: some weird hits like:
```
-=345441at2759=single 742152 955 -=345441at2759=single tr|A0A2H3IUN9|A0A2H3IUN9_WOLCO 86.9 548 69 1 3 547 2 549
```
We're still tracking where it comes from exactly, and whether a correction is needed in the pipeline or in a btk tool like `extractbuscos`

**Comment by tkchafin** [comment]
The headers lacking chromosome/position information seem to come from the btk extract buscos step. Here's the input and output headers for a small test run: 

```
#input 
(nf-core) tc25@mib119777s 42da989ff5c1643561992b272c5dae % grep ">" GCA_922984935.2.subset.phiXspike.fasta 
>OV277441.1 Meles meles genome assembly, chromosome: 1
>NC_001422.1 Escherichia phage phiX174, complete genome

#output
(nf-core) tc25@mib119777s 42da989ff5c1643561992b272c5dae % grep ">" GCA_922984935.2_buscogenes.fasta 
>-=939345at2759=single
>+=759498at2759=single
```

**Comment by rjchallis** [comment]
Could you point me to the files so I can take a look at this in context

**Comment by rjchallis** [comment]
Looks like busco 5.7+ introduced a trailing `|+` or `|-` to indicate the strand in the sequence headers which was breaking the header parsing in `extract-busco-genes`. I've added a line to strip this from the headers if present so should be working again in the develop container build from the last commit and will be in the next release.

**Comment by muffato** [comment]
Thanks ! I've kicked off a test on `develop`

**Comment by muffato** [comment]
I'm now seeing an error in BLOBTOOLKIT_CREATEBLOBDIR
```
Command executed:

  blobtools replace \
      --bedtsvdir windowstats \
      --meta GCA_927399515.1.yaml \
      --taxdump new_taxdump \
      --taxrule buscogenes \
      --busco lineage01/full_table.tsv --busco lineage02/full_table.tsv --busco lineage03/full_table.tsv --busco lineage04/full_table.tsv --busco lineage05/full_table.tsv --busco lineage06/full_table.tsv --busco lineage07/full_table.tsv \
      --hits GCA_927399515.1.txt \
      --threads 6 \
      --evalue 1.0e-25 --hit-count 10 \
      GCA_927399515.1
  
Command exit status:
  1

Command output:
  Reading all TSV files in windowstats
  Parsing taxdump

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/btk_env/bin/blobtools", line 8, in <module>
      sys.exit(cli())
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/blobtools.py", line 105, in cli
      sys.exit(subcommand())
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 203, in cli
      main(args)
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/add.py", line 149, in main
      parsed = field["module"].parse(
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 545, in parse
      blast = parse_blast(
    File "/opt/conda/envs/btk_env/lib/python3.9/site-packages/blobtools/lib/hits.py", line 103, in parse_blast
      seq_id, rest = query.split(":")
  ValueError: too many values to unpack (expected 2)

Work dir:
  /lustre/scratch123/tol/teams/tolit/users/mm49/nextflow/blobtoolkit/work/d1/e7ffcf511b1936c61cc68bc4086651
```

I guess it's trying to parse the blast results ? Here are the first 5 lines of the file. Note that it comes from diamond blastp, not blastn
```
mm49@tol22-head2:~ $ head -n 5 /lustre/scratch123/tol/teams/tolit/users/mm49/nextflow/blobtoolkit/work/d1/e7ffcf511b1936c61cc68bc4086651/GCA_927399515.1.txt 
OV656677.1:717002-717583=60954at2157=multi      914234  354     OV656677.1:717002-717583=60954at2157=multi      tr|M2QZH2|M2QZH2_CERS8  96.2    183     7       0       1       183    38       220     1.45e-127       354
OV656677.1:717002-717583=60954at2157=multi      742152  353     OV656677.1:717002-717583=60954at2157=multi      tr|A0A2H3K186|A0A2H3K186_WOLCO  95.6    183     8       0       1      183      38      220     2.64e-127       353
OV656677.1:725203-725784=60954at2157=multi      742152  347     OV656677.1:725203-725784=60954at2157=multi      tr|A0A2H3K186|A0A2H3K186_WOLCO  94.0    183     11      0       1      183      38      220     1.02e-124       347
OV656677.1:725203-725784=60954at2157=multi      914234  345     OV656677.1:725203-725784=60954at2157=multi      tr|M2QZH2|M2QZH2_CERS8  93.4    183     12      0       1       183    38       220     6.56e-124       345
OV656675.1:2535280-2536230=7724at2157=fragmented        670580  496     OV656675.1:2535280-2536230=7724at2157=fragmented        tr|A0A1X6NAI9|A0A1X6NAI9_9APHY  81.9    310     3      3
        7       316     112     368     3.14e-177       496
```

**Comment by rjchallis** [comment]
Hi Matthieu

Looks like this is happening because one of the entries has two `:` in the header

```
grep -nP ':\S+:' /lustre/scratch123/tol/teams/tolit/users/mm49/nextflow/blobtoolkit/work/d1/e7ffcf511b1936c61cc68bc4086651/GCA_927399515.1.txt
192:918816at2759_5643_1:000746|OV656676.1:915870-917297=1090038at2759=single	5643	428	918816at2759_5643_1:000746|OV656676.1:915870-917297=1090038at2759=single	tr|A0A060S6E5|A0A060S6E5_PYCCI	62.3	334	103	2	1	312	479	811	4.13e-147	428
```

This is in the headers as extracted from the busco_sequences

```
grep '>918816at2759' ce/4c96d26151a85a020c4341c6028554/GCA_927399515.1_buscogenes.fasta
>918816at2759_5643_1:000746|OV656676.1:915870-917297=1090038at2759=single
```

But things get confusing when digging deeper as the header does not match the `918816at2759.faa` file, which has the suffix `_670580_1:001fab` not `_5643_1:000746`
```
head -n 1 ce/4c96d26151a85a020c4341c6028554/lineage02/busco_sequences/single_copy_busco_sequences/918816at2759.faa
>918816at2759_670580_1:001fab|OV656676.1:917698-919603|-
```

I found the header in a the sequence file for a different busco gene
```
head -n 1 ce/4c96d26151a85a020c4341c6028554/lineage02/busco_sequences/single_copy_busco_sequences/1090038at2759.faa
>918816at2759_5643_1:000746|OV656676.1:915870-917297|-
```

and realised that the incorrect format is making it into the extracted sequences as the extract buscos script has `if header.startswith(f">{busco_id}"):` as part of its parsing logic.

So the problem is the mismatch between filename and sequence header in `busco_sequences`. If this is just a naming bug in BUSCO then I can update the script to account for it. If the bug goes deeper then I should update the script to throw an error if the filename and header don't match. 

If you can investigate this on the BUSCO side, I'll make the appropriate update once we know what is going on

**Comment by muffato** [comment]
Thanks for investigating. I can reproduce the discrepancy by running BUSCO outside of the pipeline. I'll report the bug upstream.

**Comment by muffato** [comment]
Hi Rich,
I got an answer. Essentially, it's expected that some sequence headers will differ from the file name. The headers indicate the original assignment of the sequence which may change through the different steps of the Busco pipeline. In any case, it's the filename that matters and should be used to know the name of the gene family.

**Comment by rjchallis** [comment]
Good to know it's expected behaviour, I've updated the code to allow for the mismatch. [develop container build](https://github.com/genomehubs/blobtoolkit/actions/runs/13541088801) should be ready in a few minutes

**Comment by rjchallis** [comment]
Glad it worked, this is in the 4.4.4 container release now
